repos:
  # --- ruff (линтер + форматтер) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [ --fix ]
        exclude: 'alembic/versions/'
      - id: ruff-format
        exclude: 'alembic/versions/'

  # --- mypy (статическая типизация) ---
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        exclude: 'alembic/versions/'
        additional_dependencies:
          - sqlalchemy[mypy]
          - pydantic
          - types-requests
        args:
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --check-untyped-defs
          - --no-implicit-optional

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: 'alembic/versions/'
      - id: check-json
        exclude: 'alembic/versions/'
      - id: check-toml
        exclude: 'alembic/versions/'
      - id: check-added-large-files
        exclude: 'alembic/versions/'
      - id: end-of-file-fixer
        exclude: 'alembic/versions/'
      - id: trailing-whitespace
        exclude: 'alembic/versions/'
